### ISSUE TITLE
Animer le rendu des points

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#47]
L'idée serait de rendre le classement plus vivant en ajoutant du mouvement:

![increment](https://user-images.githubusercontent.com/131776117/235175375-5bd5b2cb-70ab-4d13-b924-dace8b697885.gif)

On peut le faire en css avec un fallback pour Firefox:

```html
<div></div>
```
```css
/* https://css-tricks.com/animating-number-counters/#the-new-school-css-solution */
@property --num {
  syntax: "<integer>";
  initial-value: 0;
  inherits: false;
}

:root {
  --manif-count: 0;
}

div {
  animation: counter 3s ease-out 1;
  animation-fill-mode: forwards; 
  counter-reset: num var(--num);
}

div::after {
  content: counter(num) ' pts';
}

@keyframes counter {
  from {
    --num: 0;
  }
  to {
    --num: var(--manif-count);
  }
}
```
```js
if ("registerProperty" in window.CSS) {
  // https://stackoverflow.com/a/65135606
  document.documentElement.style.setProperty('--manif-count', 42);
} else {
  // https://stackoverflow.com/a/29261010
  const style = document.createElement("style");
  style.innerHTML = "div::after { content: '42 pts'; }";
  document.head.appendChild(style);
}
```

[Demo](https://jsfiddle.net/6dqgv402/2/)

L'alternative est de tout faire en js avec setInterval.

Je n'ai pas pris en compte des questions comme l'a11y ou la possibilité de selectionner le nombre de points. C'est pas forcément à garder comme idée.
